// BEGIN GENERATED MARQUEE BASES
// (This block is generated by scripts/generate-marquee-manifest.js)
const MARQUEE_BASES = [
  "1-1_business_chart-icon-and-flow_scale-beyond-human-limits",
  "1-1_business_monitor-graphs_10k-lost-overnight",
  "1-1_ecommerce_laptop-and-customer-hub_dms-calls-whatsapps-answered",
  "1-1_legal_desk-phone-with-scales_stop-losing-good-cases-to-voicemail",
  "1-1_marketing_boardroom-messages_your-prospects-can-tell",
  "1-1_recruitment_desk-with-candidate-ring_handle-the-next-five",
  "1-1_voiceagents_digital-dashboard_scale-beyond-human-limits",
  "2-3_accounting_man-with-holographic-call_tax-season-calls-never-missed",
  "2-3_accounting_office-with-swirling-invoices_tax-season-calls-never-missed",
  "2-3_ai_phone-processing_connect-automate-grow",
  "2-3_ai_phone-processing_connect-automate-grow 2",
  "2-3_ai_smartphone-call-completed_automate-what-matters",
  "2-3_analytics_dashboard_ai-clarity-for-human-performance",
  "2-3_auto_mechanic-with-phone_while-you-fix-cars",
  "2-3_automation_charts-scale_scale-your-output-with-ai",
  "2-3_charity_call-centre-triage_every-caller-feels-heard",
  "2-3_cleaning_phone-with-booked-job_turn-every-missed-ring",
  "2-3_cleaning_phone-with-weekly-job_turn-every-missed-ring-into-regular-client",
  "2-3_dental_black-phone-appointments_never-miss-toothache",
  "2-3_dental_phone-with-schedule_every-patient-call-answered",
  "2-3_fitness_phone-with-schedule_ai-powers-your-fitness-journey",
  "2-3_gym_phone-trial-ring_ai-calls-every-new-lead",
  "2-3_healthcare_call-queue_end-the-8am-phone-chaos",
  "2-3_healthcare_dark-call-queue_end-the-8am-phone-chaos",
  "2-3_healthcare_phone-with-appointment_ai-takes-care-of-your-patients",
  "2-3_hospitality_holographic-receptionist_your-front-desk-always-open",
  "2-3_kitchen_modern-kitchen-with-floorplan_capture-every-dream-kitchen-enquiry",
  "2-3_realestate_phone-map_never-miss-a-viewing",
  "2-3_realestate_phone-map-at-night_never-miss-a-viewing-again",
  "2-3_realestate_phone-with-house-icon_focus-on-the-viewing",
  "2-3_realestate_phone-with-property-card_ai-qualifies-your-property-leads",
  "2-3_salon_dark-chair-with-calendar_stay-fully-booked-stay-present",
  "2-3_salon_spa-room-booking-confirmed_full-treatment-list-zero-interruptions",
  "2-3_tradesman_van-at-night_never-miss-an-emergency-job",
  "2-3_veterinary_vet-with-tablet_never-miss-a-worried-pet-parent",
  "2-3_voicebot_globe-and-tablet_100k-conversations-zero-burnout",
  "3-2_business_hand-holding-phone-with-voice-display_ai-that-speaks-your-language",
  "3-2_business_laptop-at-sunset-chat-interface_when-you-wait-they-walk",
  "3-2_business_laptop-with-chat-bubbles_hours-lost-leads-unqualified",
  "3-2_business_laptop-with-sales-dashboard_your-shop-sells-while-you-sleep",
  "3-2_business_laptop-with-sales-dashboard_your-shop-sells-while-you-sleep 2",
  "3-2_childcare_tablet-in-playroom_let-ai-handle-the-parent-phone-rush",
  "3-2_legal_laptop-with-scales_ai-streamlines-legal-workflows",
  "3-2_logistics_laptop-with-truck_ai-optimises-logistics-delivery",
  "3-2_restaurant_phone-and-reservation-list_never-miss-a-booking-again",
  "3-2_sales_laptop-and-graphs_thousands-of-calls-barely-any-conversions",
  "3-2_tutoring_tutor-with-laptop_more-focused-1-1-lessons",
  "Dentists_1",
  "Dentists_2",
  "Dentists_3",
  "eComm_1",
  "eComm_2",
  "eComm_3",
  "General_Services_1",
  "General_Services_2A",
  "General_Services_2B",
  "General_Services_3",
  "Gyms_1",
  "Gyms_2",
  "Gyms_3",
  "Hospitality_1",
  "Hospitality_2",
  "Hospitality_3",
  "Online_Coach_1",
  "Online_Coach_2",
  "Online_Coach_3",
  "Physio_1",
  "Physio_2",
  "Physio_3",
  "Real_Estate_1",
  "Real_Estate_2",
  "Real_Estate_3",
  "Salon_1",
  "Salon_2",
  "Salon_3",
  "Trades_1",
  "Trades_2",
  "Trades_3",
];

const MARQUEE_MOBILE_BASES = [
  "Dentists_1",
  "Dentists_2",
  "Dentists_3",
  "eComm_1",
  "eComm_2",
  "eComm_3",
  "General_Services_1",
  "General_Services_2A",
  "General_Services_2B",
  "General_Services_3",
  "Gyms_1",
  "Gyms_2",
  "Gyms_3",
  "Hospitality_1",
  "Hospitality_2",
  "Hospitality_3",
  "Online_Coach_1",
  "Online_Coach_2",
  "Online_Coach_3",
  "Physio_1",
  "Physio_2",
  "Physio_3",
  "Real_Estate_1",
  "Real_Estate_2",
  "Real_Estate_3",
  "Salon_1",
  "Salon_2",
  "Salon_3",
  "Trades_1",
  "Trades_2",
  "Trades_3",
];
// END GENERATED MARQUEE BASES

(function () {
  'use strict';

  const ASSET_PATH = '/assets/images/socialmedia/';
  const READY_CLASS = 'marquee-ready';
  const MOBILE_BREAKPOINT = 768;

  let initialized = false;

  const mobileRenditionBases = new Set(MARQUEE_MOBILE_BASES);

  const isServicesPage = () => document.body.classList.contains('page-services');

  const isMobileViewport = () =>
    window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT}px)`).matches;

  function escapeAttrValue(value) {
    if (window.CSS && typeof window.CSS.escape === 'function') {
      return window.CSS.escape(value);
    }
    return String(value).replace(/"/g, '\\"');
  }

  function shuffleInPlace(items) {
    // Fisher–Yates shuffle
    for (let i = items.length - 1; i > 0; i -= 1) {
      const j = Math.floor(Math.random() * (i + 1));
      [items[i], items[j]] = [items[j], items[i]];
    }
    return items;
  }

  function getCandidatesForBase(base, mobile) {
    const candidates = [];
    if (mobile && mobileRenditionBases.has(base)) {
      candidates.push(
        `${base}_Mobile.webp`,
        `${base}_Mobile.jpg`,
        `${base}_Mobile.jpeg`,
      );
    }
    candidates.push(`${base}.webp`, `${base}.jpg`, `${base}.jpeg`);
    return candidates;
  }

  function setImgSrcWithFallback(img, candidates) {
    let idx = 0;
    img.src = ASSET_PATH + candidates[idx];
    img.onerror = () => {
      idx += 1;
      if (idx < candidates.length) {
        img.src = ASSET_PATH + candidates[idx];
        return;
      }
      img.style.display = 'none';
    };
  }

  function ensureLightbox() {
    if (document.getElementById('premium-lightbox')) return;

    const lightbox = document.createElement('div');
    lightbox.id = 'premium-lightbox';
    lightbox.className = 'premium-lightbox';

    const content = document.createElement('div');
    content.className = 'lightbox-content';

    const img = document.createElement('img');
    img.id = 'lightbox-img';
    img.className = 'lightbox-img';

    const closeBtn = document.createElement('button');
    closeBtn.className = 'lightbox-close';
    closeBtn.ariaLabel = 'Close Lightbox';
    closeBtn.addEventListener('click', closeLightbox);

    content.appendChild(img);
    content.appendChild(closeBtn);
    lightbox.appendChild(content);
    document.body.appendChild(lightbox);
  }

  function openLightbox(src) {
    const lightbox = document.getElementById('premium-lightbox');
    const img = document.getElementById('lightbox-img');
    if (!lightbox || !img) return;

    img.src = src;
    lightbox.classList.add('active');
    document.body.style.overflow = 'hidden';
  }

  function closeLightbox() {
    const lightbox = document.getElementById('premium-lightbox');
    if (!lightbox) return;

    lightbox.classList.remove('active');
    document.body.style.overflow = '';
  }

  function cleanupLegacyMarquees() {
    document
      .querySelectorAll(
        '.premium-marquee-container, .logo-slider, .single-marquee, .double-marquee',
      )
      .forEach((el) => el.remove());
  }

  function buildImage(base, mobile) {
    const img = document.createElement('img');
    img.className = 'marquee-img';
    img.alt = 'Silverstone Client Success';
    img.loading = 'eager'; // SPEC: MARQUEE_NO_TOUCH_REQUIRED
    img.decoding = 'async';
    img.dataset.marqueeBase = base;

    const candidates = getCandidatesForBase(base, mobile);
    setImgSrcWithFallback(img, candidates);

    img.addEventListener('click', () => openLightbox(img.src));
    return img;
  }

  function createImagesFragment(bases, mobile) {
    const fragment = document.createDocumentFragment();
    bases.forEach((base) => {
      fragment.appendChild(buildImage(base, mobile));
    });
    return fragment;
  }

  function buildSingleRow(bases, mobile) {
    const container = document.createElement('div');
    container.className = 'single-marquee';

    const track = document.createElement('div');
    track.className = 'marquee-track';

    track.appendChild(createImagesFragment(bases, mobile));
    track.appendChild(createImagesFragment(bases, mobile));

    container.appendChild(track);
    return container;
  }

  function createMarqueeRow(bases, animationClasses, mobile) {
    const track = document.createElement('div');
    track.className = `marquee-track ${animationClasses}`;

    track.appendChild(createImagesFragment(bases, mobile));
    track.appendChild(createImagesFragment(bases, mobile));

    return track;
  }

  function buildDoubleDeck(topBases, bottomBases, mobile) {
    const wrapper = document.createElement('div');
    wrapper.className = 'double-marquee';

    const topRow = createMarqueeRow(topBases, 'scroll-right fast', mobile);
    const bottomRow = createMarqueeRow(bottomBases, 'scroll-left slow', mobile);

    wrapper.appendChild(topRow);
    wrapper.appendChild(bottomRow);
    return wrapper;
  }

  function alignInnovationAnchor() {
    const hash = window.location.hash;
    if (!hash || (hash !== '#innovation-gallery' && hash !== '#neural-grid'))
      return;

    const target =
      document.getElementById('innovation-gallery') ||
      document.getElementById('neural-grid');
    if (!target) return;

    const header = document.querySelector('.site-header');
    const headerHeight = header ? header.getBoundingClientRect().height : 0;

    setTimeout(() => {
      const top =
        target.getBoundingClientRect().top + window.scrollY - headerHeight - 8;
      window.scrollTo({ top, behavior: 'auto' });
    }, 120);
  }

  function decodeSrc(src) {
    const img = new Image();
    img.decoding = 'async';
    img.src = src;

    if (typeof img.decode === 'function') {
      return img.decode().then(
        () => true,
        () => false,
      );
    }

    return new Promise((resolve) => {
      img.onload = () => resolve(true);
      img.onerror = () => resolve(false);
    });
  }

  async function resolveBaseToSrc(base) {
    const candidates = getCandidatesForBase(base, true);
    for (const filename of candidates) {
      const src = ASSET_PATH + filename;
      // Mobile ready gate: decode/preload before allowing marquee animation to run.
      if (await decodeSrc(src)) return src;
    }
    return null;
  }

  async function ensureMobileMarqueeReady() {
    if (!isMobileViewport()) {
      document.documentElement.classList.add(READY_CLASS);
      return;
    }
    if (document.documentElement.classList.contains(READY_CLASS)) return;

    const images = Array.from(
      document.querySelectorAll('img.marquee-img[data-marquee-base]'),
    );
    const bases = Array.from(
      new Set(images.map((img) => img.dataset.marqueeBase).filter(Boolean)),
    );

    const concurrency = Math.min(8, bases.length);
    let index = 0;

    async function worker() {
      while (index < bases.length) {
        const base = bases[index++];
        const resolvedSrc = await resolveBaseToSrc(base);
        const selectorBase = escapeAttrValue(base);
        const els = Array.from(
          document.querySelectorAll(
            `img.marquee-img[data-marquee-base=\"${selectorBase}\"]`,
          ),
        );

        if (!resolvedSrc) {
          els.forEach((img) => {
            img.style.display = 'none';
          });
          continue;
        }

        els.forEach((img) => {
          img.src = resolvedSrc;
        });

        await Promise.all(
          els.map((img) =>
            typeof img.decode === 'function' ? img.decode().catch(() => {}) : null,
          ),
        );
      }
    }

    await Promise.all(Array.from({ length: concurrency }, () => worker()));
    document.documentElement.classList.add(READY_CLASS);
  }

  function init() {
    if (initialized) return;
    initialized = true;

    cleanupLegacyMarquees();
    ensureLightbox();

    const mobile = isMobileViewport();
    const bases = shuffleInPlace([...MARQUEE_BASES]);

    if (isServicesPage()) {
      const topBases = bases;
      const bottomBases = shuffleInPlace([...bases]);
      const container = buildDoubleDeck(topBases, bottomBases, mobile);

      const slot = document.getElementById('innovation-marquee-slot');
      const galleryGrid = document.getElementById('neural-grid');

      if (slot) {
        slot.replaceWith(container);
      } else if (galleryGrid && galleryGrid.parentNode) {
        galleryGrid.insertAdjacentElement('afterend', container);
      } else {
        document.body.appendChild(container);
      }

      alignInnovationAnchor();
    } else {
      const footer = document.querySelector('footer.site-footer');
      if (!footer || !footer.parentNode) return;
      const marquee = buildSingleRow(bases, mobile);
      footer.parentNode.insertBefore(marquee, footer);
    }

    ensureMobileMarqueeReady().catch(() => {
      document.documentElement.classList.add(READY_CLASS);
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
