// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/how-we-work": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/services/:slug": {
    params: {
      "slug": string;
    };
  };
  "/industries": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/pricing": {
    params: {};
  };
  "/book": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/__components": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/how-we-work" | "/services" | "/services/:slug" | "/industries" | "/blog" | "/blog/:slug" | "/pricing" | "/book" | "/contact" | "/privacy-policy" | "/*" | "/__components";
  };
  "../routes/company/home.tsx": {
    id: "../routes/company/home";
    page: "/";
  };
  "../routes/company/about.tsx": {
    id: "../routes/company/about";
    page: "/about";
  };
  "../routes/company/how-we-work.tsx": {
    id: "../routes/company/how-we-work";
    page: "/how-we-work";
  };
  "../routes/services/index.tsx": {
    id: "../routes/services/index";
    page: "/services";
  };
  "../routes/services/detail.tsx": {
    id: "../routes/services/detail";
    page: "/services/:slug";
  };
  "../routes/industries/index.tsx": {
    id: "../routes/industries/index";
    page: "/industries";
  };
  "../routes/blog/index.tsx": {
    id: "../routes/blog/index";
    page: "/blog";
  };
  "../routes/blog/article.tsx": {
    id: "../routes/blog/article";
    page: "/blog/:slug";
  };
  "../routes/conversion/pricing.tsx": {
    id: "../routes/conversion/pricing";
    page: "/pricing";
  };
  "../routes/conversion/book.tsx": {
    id: "../routes/conversion/book";
    page: "/book";
  };
  "../routes/conversion/contact.tsx": {
    id: "../routes/conversion/contact";
    page: "/contact";
  };
  "../routes/legal/privacy-policy.tsx": {
    id: "../routes/legal/privacy-policy";
    page: "/privacy-policy";
  };
  "../routes/not-found.tsx": {
    id: "../routes/not-found";
    page: "/*";
  };
  "../routes/component-lab.tsx": {
    id: "../routes/component-lab";
    page: "/__components";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "../routes/company/home": unknown;
  "../routes/company/about": unknown;
  "../routes/company/how-we-work": unknown;
  "../routes/services/index": unknown;
  "../routes/services/detail": unknown;
  "../routes/industries/index": unknown;
  "../routes/blog/index": unknown;
  "../routes/blog/article": unknown;
  "../routes/conversion/pricing": unknown;
  "../routes/conversion/book": unknown;
  "../routes/conversion/contact": unknown;
  "../routes/legal/privacy-policy": unknown;
  "../routes/not-found": unknown;
  "../routes/component-lab": unknown;
};