/**
 * The Atlantic atlas: London linked to twelve US metros on a dotted world
 * plate, the instrument that opens every industry page's two-market section.
 *
 * Everything drawn on the plate is DERIVED from the coordinates and the two
 * plate definitions below — node positions, the HTML labels' percentage
 * offsets, every arc and the pulse that flies it — because five things have
 * to agree on the geometry: the static dot layers generated by
 * `scripts/generate-atlas-dots.mjs`, the SVG paths, the inline `offset-path`
 * carrying each pulse, the label positions, and the unit test. The plates are
 * equirectangular on an explicit region, so a city sits at a straight-line
 * function of its latitude and longitude, and a reader who checks Seattle
 * against Miami finds the map honest.
 *
 * PLATES is duplicated in the generator script on purpose (it is a plain
 * `.mjs` that must not import TypeScript); `tests/unit/atlas-geometry.test.ts`
 * reads the generated files' viewBox back and fails the moment the two drift.
 */

export type AtlasRegion = {
  lat: { min: number; max: number };
  lng: { min: number; max: number };
};

export type AtlasPlateName = "wide" | "compact";

type AtlasPlateSpec = {
  region: AtlasRegion;
  /** Dot-grid counts, exactly as generated. */
  width: number;
  height: number;
};

/**
 * Where a city's label sits relative to its node. Chosen per city and per
 * plate so the east-coast cluster (Boston, New York and Philadelphia are
 * within ~20px of each other at 1200) never overprints.
 */
export type AtlasAnchor = "n" | "ne" | "e" | "se" | "s" | "sw" | "w" | "nw";

export type AtlasCity = {
  id: string;
  name: string;
  lat: number;
  lng: number;
  /** IANA zone name, printed in the city strip. */
  zone: "Eastern" | "Central" | "Mountain" | "Pacific" | "GMT";
  /**
   * 1 = labelled on both plates; 2 = labelled on the wide plate only. A phone
   * plate resolves the US at ~150px across, where thirteen labels would be an
   * unreadable pile — the city strip under the plate names every metro at
   * every width instead.
   */
  tier: 1 | 2;
  anchor: Record<AtlasPlateName, AtlasAnchor>;
};

/** viewBox units per dot-grid unit. Keeps stroke widths in whole numbers. */
export const ATLAS_SCALE = 10;

export const ATLAS_PLATES: Record<AtlasPlateName, AtlasPlateSpec> = {
  /** 192° × 68°: Alaska to the Caspian, the Sahel to Svalbard. */
  wide: {
    region: { lat: { min: 4, max: 72 }, lng: { min: -140, max: 52 } },
    width: 240,
    height: 85,
  },
  /** 148° × 56°: the North Atlantic alone, so a phone plate still resolves
   * the US coastlines, with eight degrees of Pacific so the west-coast labels
   * clear the plate's edge. */
  compact: {
    region: { lat: { min: 8, max: 64 }, lng: { min: -142, max: 6 } },
    width: 111,
    height: 42,
  },
};

export const ATLAS_LAYER_HREF: Record<
  AtlasPlateName,
  Record<"world" | "us" | "uk", string>
> = {
  wide: {
    world: "/maps/atlas-wide-world.svg",
    us: "/maps/atlas-wide-us.svg",
    uk: "/maps/atlas-wide-uk.svg",
  },
  compact: {
    world: "/maps/atlas-compact-world.svg",
    us: "/maps/atlas-compact-us.svg",
    uk: "/maps/atlas-compact-uk.svg",
  },
};

export const LONDON: AtlasCity = {
  id: "london",
  name: "London",
  lat: 51.5074,
  lng: -0.1278,
  zone: "GMT",
  tier: 1,
  anchor: { wide: "e", compact: "w" },
};

/**
 * Twelve metros, chosen for size and spread: the four largest US markets,
 * the whole eastern seaboard, both Texas hubs, and a Mountain and a Pacific
 * anchor so the arcs cross all four continental time zones.
 */
export const US_METROS: readonly AtlasCity[] = [
  {
    id: "nyc",
    name: "New York",
    lat: 40.7128,
    lng: -74.006,
    zone: "Eastern",
    tier: 1,
    anchor: { wide: "e", compact: "e" },
  },
  {
    id: "bos",
    name: "Boston",
    lat: 42.3601,
    lng: -71.0589,
    zone: "Eastern",
    tier: 2,
    anchor: { wide: "ne", compact: "ne" },
  },
  {
    id: "phl",
    name: "Philadelphia",
    lat: 39.9526,
    lng: -75.1652,
    zone: "Eastern",
    tier: 2,
    anchor: { wide: "sw", compact: "sw" },
  },
  {
    id: "chi",
    name: "Chicago",
    lat: 41.8781,
    lng: -87.6298,
    zone: "Central",
    tier: 1,
    anchor: { wide: "n", compact: "n" },
  },
  {
    id: "atl",
    name: "Atlanta",
    lat: 33.749,
    lng: -84.388,
    zone: "Eastern",
    tier: 2,
    anchor: { wide: "e", compact: "e" },
  },
  {
    id: "mia",
    name: "Miami",
    lat: 25.7617,
    lng: -80.1918,
    zone: "Eastern",
    tier: 1,
    anchor: { wide: "e", compact: "e" },
  },
  {
    id: "dal",
    name: "Dallas",
    lat: 32.7767,
    lng: -96.797,
    zone: "Central",
    tier: 1,
    anchor: { wide: "w", compact: "n" },
  },
  {
    id: "hou",
    name: "Houston",
    lat: 29.7604,
    lng: -95.3698,
    zone: "Central",
    tier: 2,
    anchor: { wide: "se", compact: "se" },
  },
  {
    id: "den",
    name: "Denver",
    lat: 39.7392,
    lng: -104.9903,
    zone: "Mountain",
    tier: 2,
    anchor: { wide: "n", compact: "n" },
  },
  {
    id: "lax",
    name: "Los Angeles",
    lat: 34.0522,
    lng: -118.2437,
    zone: "Pacific",
    tier: 1,
    anchor: { wide: "s", compact: "s" },
  },
  {
    id: "sfo",
    name: "San Francisco",
    lat: 37.7749,
    lng: -122.4194,
    zone: "Pacific",
    tier: 2,
    anchor: { wide: "ne", compact: "ne" },
  },
  {
    id: "sea",
    name: "Seattle",
    lat: 47.6062,
    lng: -122.3321,
    zone: "Pacific",
    tier: 2,
    anchor: { wide: "e", compact: "e" },
  },
];

/** The continental zones the twelve metros span, for the readout. */
export const US_TIME_ZONES = [...new Set(US_METROS.map((city) => city.zone))].length;

export type AtlasPoint = { x: number; y: number };

/** One decimal: the resolution the plate is drawn at. More is noise in a path. */
const round1 = (n: number) => Math.round(n * 10) / 10;
const asPct = (value: number, span: number) =>
  `${String(round1((value / span) * 100))}%`;

/** Equirectangular: the same straight line the generator's dots sit on. */
export function projectOn(plate: AtlasPlateName, lat: number, lng: number): AtlasPoint {
  const { region, width, height } = ATLAS_PLATES[plate];
  const x = ((lng - region.lng.min) / (region.lng.max - region.lng.min)) * width;
  const y = ((region.lat.max - lat) / (region.lat.max - region.lat.min)) * height;
  return { x: round1(x * ATLAS_SCALE), y: round1(y * ATLAS_SCALE) };
}

/** How far north of its chord an arc bows, as a fraction of the chord. */
const ARC_LIFT = 0.22;
/** The arc's apex never rises above this fraction of the plate's height. */
const ARC_APEX_MIN = 0.08;

/**
 * The quadratic's control point: the chord's midpoint lifted north by a fixed
 * fraction of the chord, so a longer link bows more — the flat-projection
 * signature of a great circle — and every arc from one hub reads as one
 * family. The lift is clamped so the arc's apex (the curve at t = 0.5) stays
 * inside the plate: Seattle to London is long enough that an unclamped bow
 * would peak above the compact plate's top edge and be clipped.
 */
export function arcControl(
  from: AtlasPoint,
  to: AtlasPoint,
  plateHeight: number,
): AtlasPoint {
  const chord = Math.hypot(to.x - from.x, to.y - from.y);
  const midY = (from.y + to.y) / 2;
  // apex.y = (from.y + 2·ctrl.y + to.y) / 4, so the lowest control point that
  // keeps the apex at or below ARC_APEX_MIN · h is:
  const floor = (4 * ARC_APEX_MIN * plateHeight - from.y - to.y) / 2;
  return {
    x: round1((from.x + to.x) / 2),
    y: round1(Math.max(midY - chord * ARC_LIFT, floor)),
  };
}

export function arcPath(from: AtlasPoint, ctrl: AtlasPoint, to: AtlasPoint): string {
  return `M ${String(from.x)} ${String(from.y)} Q ${String(ctrl.x)} ${String(ctrl.y)} ${String(to.x)} ${String(to.y)}`;
}

/** The quadratic at t, used for the parked (reduced-motion) pulse. */
export function quadAt(
  from: AtlasPoint,
  ctrl: AtlasPoint,
  to: AtlasPoint,
  t: number,
): AtlasPoint {
  const u = 1 - t;
  return {
    x: round1(u * u * from.x + 2 * u * t * ctrl.x + t * t * to.x),
    y: round1(u * u * from.y + 2 * u * t * ctrl.y + t * t * to.y),
  };
}

export type AtlasNode = AtlasCity & {
  point: AtlasPoint;
  /** Percentage offsets for the HTML label over the plate box. */
  at: { x: string; y: string };
  /** Which anchor this plate uses. */
  side: AtlasAnchor;
  /** Whether this plate prints the label at all. */
  labelled: boolean;
};

export type AtlasLink = {
  city: AtlasNode;
  ctrl: AtlasPoint;
  /** City → London. The pulse direction is flipped in CSS per market. */
  path: string;
  park: AtlasPoint;
};

export type AtlasPlate = {
  name: AtlasPlateName;
  w: number;
  h: number;
  viewBox: string;
  hub: AtlasNode;
  cities: AtlasNode[];
  links: AtlasLink[];
  layers: Record<"world" | "us" | "uk", string>;
};

function nodeOn(
  plate: AtlasPlateName,
  city: AtlasCity,
  w: number,
  h: number,
): AtlasNode {
  const point = projectOn(plate, city.lat, city.lng);
  return {
    ...city,
    point,
    at: { x: asPct(point.x, w), y: asPct(point.y, h) },
    side: city.anchor[plate],
    labelled: plate === "wide" || city.tier === 1,
  };
}

export function buildAtlasPlate(name: AtlasPlateName): AtlasPlate {
  const spec = ATLAS_PLATES[name];
  const w = spec.width * ATLAS_SCALE;
  const h = spec.height * ATLAS_SCALE;
  const hub = nodeOn(name, LONDON, w, h);
  const cities = US_METROS.map((city) => nodeOn(name, city, w, h));
  const links = cities.map((city) => {
    const ctrl = arcControl(city.point, hub.point, h);
    return {
      city,
      ctrl,
      path: arcPath(city.point, ctrl, hub.point),
      /* Mid-flight, so a reader on reduced motion still sees the link as in
         transit rather than as a dead line. */
      park: quadAt(city.point, ctrl, hub.point, 0.58),
    };
  });
  return {
    name,
    w,
    h,
    viewBox: `0 0 ${String(w)} ${String(h)}`,
    hub,
    cities,
    links,
    layers: ATLAS_LAYER_HREF[name],
  };
}

export const ATLAS_WIDE = buildAtlasPlate("wide");
export const ATLAS_COMPACT = buildAtlasPlate("compact");
