/**
 * The Atlantic atlas: London and twelve US metros on a dotted world plate,
 * the instrument that opens every industry page's two-market section.
 *
 * Everything drawn on the plate is DERIVED from the coordinates and the two
 * plate definitions below — node positions, the HTML labels' percentage
 * offsets, every arc, each country's glow — because four things have to
 * agree on the geometry: the static dot layers generated by
 * `scripts/generate-atlas-dots.mjs`, the SVG paths, the label positions, and
 * the unit test. The plates are equirectangular on an explicit region, so a
 * city sits at a straight-line function of its latitude and longitude, and a
 * reader who checks Seattle against Miami finds the map honest.
 *
 * PLATES is duplicated in the generator script on purpose (it is a plain
 * `.mjs` that must not import TypeScript); `tests/unit/atlas-geometry.test.ts`
 * reads the generated files' viewBox back and fails the moment the two drift.
 */

export type AtlasRegion = {
  lat: { min: number; max: number };
  lng: { min: number; max: number };
};

export type AtlasPlateName = "wide" | "compact" | "phone";

/** The two ocean plates: one equirectangular region each. */
export type AtlasRegionPlateName = "wide" | "compact";

type AtlasPlateSpec = {
  region: AtlasRegion;
  /** Dot-grid counts, exactly as generated. */
  width: number;
  height: number;
};

/**
 * Where a city's label sits relative to its node. Chosen per city and per
 * plate so the east-coast cluster (Boston, New York and Philadelphia are
 * within ~20px of each other at 1200) never overprints.
 */
export type AtlasAnchor = "n" | "ne" | "e" | "se" | "s" | "sw" | "w" | "nw";

export type AtlasCity = {
  id: string;
  name: string;
  lat: number;
  lng: number;
  /** IANA zone name, printed in the city strip. */
  zone: "Eastern" | "Central" | "Mountain" | "Pacific" | "GMT";
  /**
   * How much of the plate a metro claims.
   *
   *   1 — labelled on both plates and linked to London by a drawn route.
   *   2 — labelled on the wide plate only, still linked.
   *   3 — plotted as a quiet node, never labelled, never linked.
   *
   * Twelve routes converging on one hub read as a fan, and thirteen labels
   * on a ~1100px plate piled the east coast three deep, so only the seven
   * best-spread metros carry a route and a name on the wide plate; a phone
   * plate resolves the US at ~150px across and keeps the first tier alone.
   * The city strip under the plate names every metro at every width, so
   * nothing a reader might search for leaves the page.
   */
  tier: 1 | 2 | 3;
  anchor: Record<AtlasPlateName, AtlasAnchor>;
};

/** viewBox units per dot-grid unit. Keeps stroke widths in whole numbers. */
export const ATLAS_SCALE = 10;

export const ATLAS_PLATES: Record<AtlasRegionPlateName, AtlasPlateSpec> = {
  /** 192° × 68°: Alaska to the Caspian, the Sahel to Svalbard. */
  wide: {
    region: { lat: { min: 4, max: 72 }, lng: { min: -140, max: 52 } },
    width: 240,
    height: 85,
  },
  /** 148° × 56°: the North Atlantic alone, so a phone plate still resolves
   * the US coastlines, with eight degrees of Pacific so the west-coast labels
   * clear the plate's edge. */
  compact: {
    region: { lat: { min: 8, max: 64 }, lng: { min: -142, max: 6 } },
    width: 111,
    height: 42,
  },
};

/*
 * ---- The phone plate --------------------------------------------------------
 *
 * Below 40rem one North-Atlantic region no longer works: at ~270px across it
 * resolved the US at 130px and the UK as a dozen dots cut off at the right
 * edge. The phone plate is two INSETS on one plate instead — the continental
 * US across the top at full width, the British Isles below it on the right —
 * each an honest equirectangular region at its own scale (0.8° per dot for
 * the US, 0.4° for the UK, so the island finally has a coastline). London's
 * routes leave the UK inset and land on the US one; the arcs are the bridge.
 * The desktop and tablet plates are untouched.
 */
export type AtlasInsetName = "us" | "uk";

export type AtlasInsetSpec = AtlasPlateSpec & {
  /** The inset's origin on the phone plate, in dot-grid units. */
  x: number;
  y: number;
};

export const ATLAS_PHONE_INSETS: Record<AtlasInsetName, AtlasInsetSpec> = {
  /** 60° × 30° at 1.667 dots per degree: Seattle to Maine, the Rio Grande to
   * the 49th parallel, with a degree and a half of sea above Seattle and
   * below Miami so neither label sits on the frame. The inset is the whole
   * plate width less the margins — which is why New York's phone label sits
   * under its node rather than east of it (see `US_METROS`). */
  us: {
    region: { lat: { min: 21, max: 51 }, lng: { min: -126, max: -66 } },
    width: 100,
    height: 50,
    x: 3,
    y: 3,
  },
  /** 14° × 10° at 3 dots per degree: a degree of Atlantic west of Ireland to
   * the North Sea off the Belgian coast, the Channel to the Orkneys.
   * Deliberately the smaller frame — the same proportion to the US inset as
   * the original plate had — so the island reads as an inset and not as a
   * second map of equal weight. The region sits a degree further west than
   * the ocean plates' UK crop so London lands east of Boston on a plate
   * whose US inset now runs to the east margin (`reads honestly` test). */
  uk: {
    region: { lat: { min: 49.5, max: 59.5 }, lng: { min: -12, max: 2 } },
    width: 42,
    height: 30,
    x: 61,
    y: 56,
  },
};

/** The phone plate's own grid: a three-dot margin all round (the chart's
 * 20px corner radius would otherwise cut an inset's own corner), the US
 * inset across the full width, and the UK inset seated under it at the east
 * edge with a gutter between. The UK inset is east so London stays east of
 * New York: the plate must read the same way the ocean plates do. The plate
 * is drawn at the page's full width on a phone, ~3.2px a dot at 375. */
export const ATLAS_PHONE_GRID = { width: 106, height: 89 } as const;

export const ATLAS_PHONE_LAYER_HREF: Record<
  AtlasInsetName,
  { world: string; land: string }
> = {
  us: { world: "/maps/atlas-phone-us-world.svg", land: "/maps/atlas-phone-us-us.svg" },
  uk: { world: "/maps/atlas-phone-uk-world.svg", land: "/maps/atlas-phone-uk-uk.svg" },
};

export const ATLAS_LAYER_HREF: Record<
  AtlasRegionPlateName,
  Record<"world" | "us" | "uk", string>
> = {
  wide: {
    world: "/maps/atlas-wide-world.svg",
    us: "/maps/atlas-wide-us.svg",
    uk: "/maps/atlas-wide-uk.svg",
  },
  compact: {
    world: "/maps/atlas-compact-world.svg",
    us: "/maps/atlas-compact-us.svg",
    uk: "/maps/atlas-compact-uk.svg",
  },
};

export const LONDON: AtlasCity = {
  id: "london",
  name: "London",
  lat: 51.5074,
  lng: -0.1278,
  zone: "GMT",
  tier: 1,
  anchor: { wide: "e", compact: "w", phone: "w" },
};

/**
 * Twelve metros, chosen for size and spread: the four largest US markets,
 * the whole eastern seaboard, both Texas hubs, and a Mountain and a Pacific
 * anchor so the arcs cross all four continental time zones.
 */
export const US_METROS: readonly AtlasCity[] = [
  {
    id: "nyc",
    name: "New York",
    lat: 40.7128,
    lng: -74.006,
    zone: "Eastern",
    tier: 1,
    /* South-east on the wide plate: due east sat squarely over Boston's
       node, which is 13px east and 8px north of New York's at 1200. South
       on the phone: the US inset runs to the plate's east margin there, so
       an eastward name (~70px, a fifth of the plate) would leave the plate;
       south clears Boston to the north-east and sits a dot under
       Philadelphia's quiet node. */
    anchor: { wide: "se", compact: "e", phone: "s" },
  },
  {
    id: "bos",
    name: "Boston",
    lat: 42.3601,
    lng: -71.0589,
    zone: "Eastern",
    tier: 3,
    anchor: { wide: "ne", compact: "ne", phone: "ne" },
  },
  {
    id: "phl",
    name: "Philadelphia",
    lat: 39.9526,
    lng: -75.1652,
    zone: "Eastern",
    tier: 3,
    anchor: { wide: "sw", compact: "sw", phone: "sw" },
  },
  {
    id: "chi",
    name: "Chicago",
    lat: 41.8781,
    lng: -87.6298,
    zone: "Central",
    tier: 1,
    anchor: { wide: "n", compact: "n", phone: "n" },
  },
  {
    id: "atl",
    name: "Atlanta",
    lat: 33.749,
    lng: -84.388,
    zone: "Eastern",
    tier: 3,
    anchor: { wide: "e", compact: "e", phone: "e" },
  },
  {
    id: "mia",
    name: "Miami",
    lat: 25.7617,
    lng: -80.1918,
    zone: "Eastern",
    tier: 1,
    anchor: { wide: "e", compact: "e", phone: "e" },
  },
  {
    id: "dal",
    name: "Dallas",
    lat: 32.7767,
    lng: -96.797,
    zone: "Central",
    tier: 1,
    /* North on the wide plate: west ran the name straight into Los Angeles's
       label (south of its node, 270 units away) at every desktop width, and
       south or east would sit on Houston's or Atlanta's node. */
    anchor: { wide: "n", compact: "n", phone: "n" },
  },
  {
    id: "hou",
    name: "Houston",
    lat: 29.7604,
    lng: -95.3698,
    zone: "Central",
    tier: 3,
    anchor: { wide: "se", compact: "se", phone: "se" },
  },
  {
    id: "den",
    name: "Denver",
    lat: 39.7392,
    lng: -104.9903,
    zone: "Mountain",
    tier: 2,
    /* North-west on the phone: due north met Seattle's name coming in from
       the west on a 375px plate. */
    anchor: { wide: "n", compact: "n", phone: "nw" },
  },
  {
    id: "lax",
    name: "Los Angeles",
    lat: 34.0522,
    lng: -118.2437,
    zone: "Pacific",
    tier: 1,
    /* South-east on the phone: centred below, the name ran off the inset's
       west edge, and due east sat under Dallas's label. */
    anchor: { wide: "s", compact: "s", phone: "se" },
  },
  {
    id: "sfo",
    name: "San Francisco",
    lat: 37.7749,
    lng: -122.4194,
    zone: "Pacific",
    tier: 3,
    anchor: { wide: "ne", compact: "ne", phone: "w" },
  },
  {
    id: "sea",
    name: "Seattle",
    lat: 47.6062,
    lng: -122.3321,
    zone: "Pacific",
    tier: 2,
    anchor: { wide: "e", compact: "e", phone: "e" },
  },
];

/** The continental zones the twelve metros span, for the readout. */
export const US_TIME_ZONES = [...new Set(US_METROS.map((city) => city.zone))].length;

/** Metros that carry a drawn route to London: the first two tiers. */
export const LINKED_METROS: readonly AtlasCity[] = US_METROS.filter(
  (city) => city.tier <= 2,
);

export type AtlasPoint = { x: number; y: number };

/** One decimal: the resolution the plate is drawn at. More is noise in a path. */
const round1 = (n: number) => Math.round(n * 10) / 10;
const asPct = (value: number, span: number) =>
  `${String(round1((value / span) * 100))}%`;

/** Equirectangular: the same straight line the generator's dots sit on. */
function projectInRegion(
  spec: AtlasPlateSpec,
  lat: number,
  lng: number,
  origin: AtlasPoint = { x: 0, y: 0 },
): AtlasPoint {
  const { region, width, height } = spec;
  const x = ((lng - region.lng.min) / (region.lng.max - region.lng.min)) * width;
  const y = ((region.lat.max - lat) / (region.lat.max - region.lat.min)) * height;
  return {
    x: round1((origin.x + x) * ATLAS_SCALE),
    y: round1((origin.y + y) * ATLAS_SCALE),
  };
}

export function projectOn(
  plate: AtlasRegionPlateName,
  lat: number,
  lng: number,
): AtlasPoint {
  return projectInRegion(ATLAS_PLATES[plate], lat, lng);
}

/** The same line, on one of the phone plate's insets, in plate coordinates. */
export function projectOnInset(
  inset: AtlasInsetName,
  lat: number,
  lng: number,
): AtlasPoint {
  const spec = ATLAS_PHONE_INSETS[inset];
  return projectInRegion(spec, lat, lng, { x: spec.x, y: spec.y });
}

/** How far north of its chord an arc bows, as a fraction of the chord. */
const ARC_LIFT = 0.22;
/** The arc's apex never rises above this fraction of the plate's height. */
const ARC_APEX_MIN = 0.08;

/**
 * The quadratic's control point: the chord's midpoint lifted north by a fixed
 * fraction of the chord, so a longer link bows more — the flat-projection
 * signature of a great circle — and every arc from one hub reads as one
 * family. The lift is clamped so the arc's apex (the curve at t = 0.5) stays
 * inside the plate: Seattle to London is long enough that an unclamped bow
 * would peak above the compact plate's top edge and be clipped.
 */
export function arcControl(
  from: AtlasPoint,
  to: AtlasPoint,
  plateHeight: number,
): AtlasPoint {
  const chord = Math.hypot(to.x - from.x, to.y - from.y);
  const midY = (from.y + to.y) / 2;
  // apex.y = (from.y + 2·ctrl.y + to.y) / 4, so the lowest control point that
  // keeps the apex at or below ARC_APEX_MIN · h is:
  const floor = (4 * ARC_APEX_MIN * plateHeight - from.y - to.y) / 2;
  return {
    x: round1((from.x + to.x) / 2),
    y: round1(Math.max(midY - chord * ARC_LIFT, floor)),
  };
}

export function arcPath(from: AtlasPoint, ctrl: AtlasPoint, to: AtlasPoint): string {
  return `M ${String(from.x)} ${String(from.y)} Q ${String(ctrl.x)} ${String(ctrl.y)} ${String(to.x)} ${String(to.y)}`;
}

/** The quadratic at t: the apex (t = 0.5) is what the geometry test checks. */
export function quadAt(
  from: AtlasPoint,
  ctrl: AtlasPoint,
  to: AtlasPoint,
  t: number,
): AtlasPoint {
  const u = 1 - t;
  return {
    x: round1(u * u * from.x + 2 * u * t * ctrl.x + t * t * to.x),
    y: round1(u * u * from.y + 2 * u * t * ctrl.y + t * t * to.y),
  };
}

export type AtlasNode = AtlasCity & {
  point: AtlasPoint;
  /** Percentage offsets for the HTML label over the plate box. */
  at: { x: string; y: string };
  /** Which anchor this plate uses. */
  side: AtlasAnchor;
  /** Whether this plate prints the label at all. */
  labelled: boolean;
  /** Whether a route is drawn between this node and London. */
  linked: boolean;
};

export type AtlasLink = {
  city: AtlasNode;
  ctrl: AtlasPoint;
  /**
   * London → city, so a `stroke-dashoffset` draw runs outward from the hub:
   * the routes power on as one signal leaving London for the metros.
   */
  path: string;
  /**
   * Draw order, 0 = the shortest route. The power-on staggers by this rather
   * than by array position, so the signal reaches the near coast first and
   * the Pacific last, the way a real fan-out would.
   */
  rank: number;
};

/** A soft ellipse of light under one country's dots: its glow. */
export type AtlasAura = { cx: number; cy: number; rx: number; ry: number };

/** One of the phone plate's framed regions, in viewBox units. */
export type AtlasInset = {
  x: number;
  y: number;
  w: number;
  h: number;
  /** viewBox units per 10° of longitude: the inset's graticule pitch. */
  graticule: number;
  layers: { world: string; land: string };
};

export type AtlasPlate = {
  name: AtlasPlateName;
  w: number;
  h: number;
  viewBox: string;
  hub: AtlasNode;
  cities: AtlasNode[];
  links: AtlasLink[];
  aura: Record<"us" | "uk", AtlasAura>;
  /** The ocean plates' three full-plate layers; the phone plate draws its
   * insets' layers instead (see `insets`). */
  layers: Record<"world" | "us" | "uk", string>;
  insets?: Record<AtlasInsetName, AtlasInset>;
};

/** An ocean plate: one region, so its name indexes `ATLAS_PLATES`. */
export type AtlasRegionPlate = Omit<AtlasPlate, "name" | "insets"> & {
  name: AtlasRegionPlateName;
};

function nodeAt(
  plate: AtlasPlateName,
  city: AtlasCity,
  point: AtlasPoint,
  w: number,
  h: number,
): AtlasNode {
  return {
    ...city,
    point,
    at: { x: asPct(point.x, w), y: asPct(point.y, h) },
    side: city.anchor[plate],
    /* The wide plate and the phone plate have room for the second tier (the
       phone's US inset is 240px across, the wide plate's US 360); the compact
       plate resolves the US at ~150px and keeps the first tier alone. */
    labelled: city.tier === 1 || (plate !== "compact" && city.tier === 2),
    linked: city.tier <= 2,
  };
}

function nodeOn(
  plate: AtlasRegionPlateName,
  city: AtlasCity,
  w: number,
  h: number,
): AtlasNode {
  return nodeAt(plate, city, projectOn(plate, city.lat, city.lng), w, h);
}

/** viewBox units per degree of longitude in a region, for sizing the auras. */
function unitsPerDegreeIn(spec: AtlasPlateSpec): number {
  return (spec.width * ATLAS_SCALE) / (spec.region.lng.max - spec.region.lng.min);
}

function unitsPerDegree(plate: AtlasRegionPlateName): number {
  return unitsPerDegreeIn(ATLAS_PLATES[plate]);
}

/**
 * The US glow is fitted to the metros' own extent — the ellipse that covers
 * the twelve nodes with a margin — so it lights the country the routes land
 * in, not an arbitrary disc. The UK is too small to fit to one node, so its
 * glow is a fixed few degrees around the island's centre.
 */
function aurasFor(
  cities: AtlasNode[],
  usUnit: number,
  uk: AtlasPoint,
  ukUnit: number,
): Record<"us" | "uk", AtlasAura> {
  const xs = cities.map((city) => city.point.x);
  const ys = cities.map((city) => city.point.y);
  const west = Math.min(...xs);
  const east = Math.max(...xs);
  const north = Math.min(...ys);
  const south = Math.max(...ys);
  return {
    us: {
      cx: round1((west + east) / 2),
      cy: round1((north + south) / 2),
      rx: round1(((east - west) / 2) * 1.3 + usUnit * 2),
      ry: round1(((south - north) / 2) * 1.35 + usUnit * 2.5),
    },
    uk: {
      cx: uk.x,
      cy: uk.y,
      rx: round1(ukUnit * 6.5),
      ry: round1(ukUnit * 6),
    },
  };
}

function aurasOn(
  plate: AtlasRegionPlateName,
  cities: AtlasNode[],
): Record<"us" | "uk", AtlasAura> {
  const unit = unitsPerDegree(plate);
  return aurasFor(cities, unit, projectOn(plate, 54.4, -2.8), unit);
}

/** The routes, London first, ranked nearest metro first. */
function linksFrom(hub: AtlasNode, cities: AtlasNode[], h: number): AtlasLink[] {
  const linked = cities.filter((city) => city.linked);
  const byChord = [...linked].sort(
    (a, b) =>
      Math.hypot(hub.point.x - a.point.x, hub.point.y - a.point.y) -
      Math.hypot(hub.point.x - b.point.x, hub.point.y - b.point.y),
  );
  return linked.map((city) => {
    const ctrl = arcControl(hub.point, city.point, h);
    return {
      city,
      ctrl,
      path: arcPath(hub.point, ctrl, city.point),
      rank: byChord.indexOf(city),
    };
  });
}

export function buildAtlasPlate(name: AtlasRegionPlateName): AtlasRegionPlate {
  const spec = ATLAS_PLATES[name];
  const w = spec.width * ATLAS_SCALE;
  const h = spec.height * ATLAS_SCALE;
  const hub = nodeOn(name, LONDON, w, h);
  const cities = US_METROS.map((city) => nodeOn(name, city, w, h));
  return {
    name,
    w,
    h,
    viewBox: `0 0 ${String(w)} ${String(h)}`,
    hub,
    cities,
    links: linksFrom(hub, cities, h),
    aura: aurasOn(name, cities),
    layers: ATLAS_LAYER_HREF[name],
  };
}

function insetBox(name: AtlasInsetName): AtlasInset {
  const spec = ATLAS_PHONE_INSETS[name];
  return {
    x: spec.x * ATLAS_SCALE,
    y: spec.y * ATLAS_SCALE,
    w: spec.width * ATLAS_SCALE,
    h: spec.height * ATLAS_SCALE,
    graticule: round1(unitsPerDegreeIn(spec) * 10),
    layers: ATLAS_PHONE_LAYER_HREF[name],
  };
}

/**
 * The phone plate: every metro projected on the US inset, London on the UK
 * one, and the routes drawn between them in the plate's shared coordinates.
 * The US glow is fitted to the metros at the US inset's scale; the UK glow is
 * the island's own few degrees at the UK inset's much larger one.
 */
export function buildPhoneAtlas(): AtlasPlate {
  const w = ATLAS_PHONE_GRID.width * ATLAS_SCALE;
  const h = ATLAS_PHONE_GRID.height * ATLAS_SCALE;
  const hub = nodeAt(
    "phone",
    LONDON,
    projectOnInset("uk", LONDON.lat, LONDON.lng),
    w,
    h,
  );
  const cities = US_METROS.map((city) =>
    nodeAt("phone", city, projectOnInset("us", city.lat, city.lng), w, h),
  );
  return {
    name: "phone",
    w,
    h,
    viewBox: `0 0 ${String(w)} ${String(h)}`,
    hub,
    cities,
    links: linksFrom(hub, cities, h),
    aura: aurasFor(
      cities,
      unitsPerDegreeIn(ATLAS_PHONE_INSETS.us),
      projectOnInset("uk", 54.4, -2.8),
      unitsPerDegreeIn(ATLAS_PHONE_INSETS.uk),
    ),
    layers: {
      world: ATLAS_PHONE_LAYER_HREF.us.world,
      us: ATLAS_PHONE_LAYER_HREF.us.land,
      uk: ATLAS_PHONE_LAYER_HREF.uk.land,
    },
    insets: { us: insetBox("us"), uk: insetBox("uk") },
  };
}

export const ATLAS_WIDE = buildAtlasPlate("wide");
export const ATLAS_COMPACT = buildAtlasPlate("compact");
export const ATLAS_PHONE = buildPhoneAtlas();
